### ISSUE TITLE
Non-minimized build of amazon-cognito-identity.min.js

### ISSUE THREAD

**Issue by kennu** [aws/amazon-cognito-identity-js#104]
It would be useful to provide a non-minimized build of `amazon-cognito-identity.min.js` for incorporating into builds that do their own minimization.

(Currently I need to download and update the various individual components separately.)

**Comment by simonbuchan** [comment]
Are the bundle source maps not working for you? Your build might be simply missing something, for example [gulp-sourcemap needs a `loadMaps` option](https://www.npmjs.com/package/gulp-sourcemaps#load-existing-source-maps) to enable forwarding the existing source mapping.

**Comment by simonbuchan** [comment]
And for webpack, https://github.com/webpack/source-map-loader

**Comment by kennu** [comment]
So, non-minimized version not happening? I need to concatenate all kinds of .js files together to make this library work (jsbn.js, jsbn2.js, sjcl.js, moment.js, aws-cognito-sdk.js, amazon-cognito-identity-js.js) and I'd prefer that big concatenated file to not contain some minimized code in the middle.

Of course, it would be even nicer to not have to patch all those dependencies together manually.

**Comment by simonbuchan** [comment]
If source maps are working right your debugger, stack traces, etc should all be pointing at the actual source files, like [/src/CognitoUserPool.js](https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUserPool.js) - a merely non-minimised build would have a bunch of webpack and babel cruft to sort through still, since #108 was merged at least.

So essentially, no. You are much better served getting your source maps generated correctly if you care about debugging in library code, maybe try out the updated webpack usage docs in the readme and let me know if they're missing something.

**Comment by simonbuchan** [comment]
If you really want a friendlier bundled file, clone the repo and run `npm install` then `node_modules/.bin/webpack -d`

**Comment by kennu** [comment]
The updated documentation on how to `npm install` dependencies looks good, thanks! I'll try to do that instead of all the manual concatenation

(My build process has been based on the older documentation which instructed to manually download individual files from various links.)

**Comment by kennu** [comment]
Just wanted to say that the Webpack/Babel based build process works really nicely for me, very simple to import the classes directly from the package. Thanks for making it easy.

Had some trouble first because my Phenomic project included a default `noParse: /\.min\.js/` clause, which caused a "require not defined" error from the Cognito SDK. Removing the clause fixed it.
