### ISSUE TITLE
big number implementation with sjcl.bn instead of with jsbn

### ISSUE THREAD

**Issue by borisirota** [aws/amazon-cognito-identity-js#110]
Its more a question than an issue

_I don't know much about BigNumber implementation and already using custom build of `sjcl` with the `bn` implementation_

In general, is this lib can achieve the same result while using the `sjcl.bn` instead of `jsbn` in order to reduce the bundle size for users that already using sjcl like me ? or is there some features that exist only in the `jsbn` lib ?

If its possible, is there a motivation for you guys to go in that direction (e.g. minimum external dependencies) ?

Thanks

**Comment by itrestian** [comment]
I took a look at most big integer libraries out there when I implemented this and as I recall this was the fastest. Some were missing the modPow function. Are the methods exposed by the sjcl big integer implementation different? Most libraries I could just plug them in and they would work since they expose the same functions.

https://github.com/aws/amazon-cognito-identity-js/pull/43
