### ISSUE TITLE
set answerCorrect to true, client always show 'Unrecognizable lambda output'

### ISSUE THREAD

**Issue by realkyo** [aws/amazon-cognito-identity-js#167]
Hi,
I run this trigger sample case: 'Verify Auth Challenge Response Example'
http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#aws-lambda-triggers-verify-auth-challenge-response-example

exports.handler = function(event, context) {
    if (event.request.privateChallengeParameters.answer == event.request.challengeAnswer) {
        event.response.answerCorrect = true;
    } else {
        event.response.answerCorrect = false;
    }

```
context.done(null, event);
```

}

browser side always show error message when run into event.response.answerCorrect = true;

x-amzn-ErrorMessage: Unrecognizable lambda output
x-amzn-ErrorType: InvalidLambdaResponseException:
x-amzn-RequestId: d049b348-893d-11e6-b52a-c19cddcd7c48

there's something missing?

**Comment by itrestian** [comment]
How are you calling this? Note that verify auth challenge response is the last lambda called in the authentication chain. The define and create custom auth challenge lambdas are called before them and they might be failing as well.

**Comment by itrestian** [comment]
Is this still occurring?

**Comment by itrestian** [comment]
Closing, feel free to reopen if this still occurs.

**Comment by robertbrower-technologies** [comment]
Good morning. Question about Cognito & Lambda. I have attached a onPostAuthentication Lambda function to the Post Authentication trigger of my user pool so that I can pass important information back to my web app after the user authenticates. I am not modifying the event because the docs say that the event should not be modified. Instead I am calling callback(null, someObject) after calling context.done(null, event). I cannot figure how to not get the "Unrecognizable lambda output" in this situation. Can anyone help? Thank you.
