### ISSUE TITLE
After changing email, user cannot authenticate via the new email

### ISSUE THREAD

**Issue by codynguyen** [aws/amazon-cognito-identity-js#169]
Hi,

We are using Cognito User Pool in our website for authentication. Initially email is set as alias and users can authenticate via their email.

However, if a user changes his email (from `a@mail.com` to `b@mail.com` and confirms it), he cannot log in with the new email (`b@mail.com`). He can still use the old email (`a@mail.com`) to log in.

Looking at Cognito Console, the user's username is still `a@mail.com` in the Users list. When clicking on the user to see his details, it shows email as `b@mail.com` and email_verified as `true`.

Not sure if this is a bug or a missing feature? I can't find any documentation mentioning this case. Any help is greatly appreciated

Thanks!

**Comment by kushwahavinay** [comment]
Can you please check if you have set the email as an alias attribute in your user pool settings?
Looks like not, because if you set alias on email, username is not allowed to be of email format.
You can find more details about alias feature in our [developer guide.](http://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html)
By design username will remain fixed, but the alias can change.

**Comment by codynguyen** [comment]
@kushwahavinay you're right, I just checked and see that email alias box is not checked. I consciously decided to use email as alias, but not sure how it turned out to be the other way around now.

Thank you very much!
