### ISSUE TITLE
How to mock global AWS variable

### ISSUE THREAD

**Issue by anilreddykatta** [aws/amazon-cognito-identity-js#278]
I am trying to write unit tests with JEST. Currently I am using webpack, react, babel in my project. As we have AWS declared as a global variable, how can I mock it to write unit tests?

**Comment by sbussard** [comment]
Personally I'm not a fan of having to mock things out to test them, it feels brittle. 
What you're describing is actually an integration test - to see how well your code integrates with AWS. 

I recommend isolating your code that depends on AWS into a single location (same file or folder). Example: src/util/aws.js or src/util/aws/cognito.js ... 

Inside of your functions you don't want to get too involved with mocking out what the AWS object looks like, because that is subject to change over time and you'll have to update your tests every time. Instead, create spies (in jasmine.js for example) to make sure certain functions of yours call certain functions of AWS, but stay as shallow as possible in the tree structure. 

This question would be a good candidate to post on stackoverflow.com

**Comment by itrestian** [comment]
@sbussard 's answer is right on point.
