### ISSUE TITLE
cognitoUser.authenticateUser doesn't work with cordova ios ipad 2 and 3

### ISSUE THREAD

**Issue by happygts** [aws/amazon-cognito-identity-js#304]
Hey guys,

I have an issue with the authenticateUser with the ipad 2 and 3.
My code works with all of the android/ios devices exept with these two.

I saw these issues : #43 #58 

I understand that it's a performance issue, but I really don't understand how to fix this.
If someone has an idea ?

**Comment by itrestian** [comment]
The Amazon Cognito Identity JavaScript SDK has a dependency on the main AWS JavaScript SDK which can be used in the browser and Node.js so other environments might not work correctly. We rely on it to make the Cognito service calls.

http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.ht...

For iOS and Android, we recommend developers to go native and we have SDKs available for both platforms. Customers have indeed reported that hybrid platforms such as PhoneGap or Cordova are slower on older devices because of the big integer computations involved as part of the SRP protocol.

Also, do you guys have device tracking enabled. If so, is disabling device tracking on older devices an option for your use case? This might speed up the authentication process.

**Comment by happygts** [comment]
Ok, I will try to make a native implementation and make a cordova plugin to make it all work, I will let you know.

Thanks

**Comment by itrestian** [comment]
Should work to use the native bridge similar to this issue and it might get a better performance.

https://github.com/aws/amazon-cognito-identity-js/issues/195

**Comment by itrestian** [comment]
Seems you have solved this issue:

https://github.com/aws/aws-sdk-ios/issues/609

Closing, feel free to reopen if necessary.
