### ISSUE TITLE
autoconfirm user with resetpassword

### ISSUE THREAD

**Issue by abhishekpalavancha** [aws/amazon-cognito-identity-js#328]
Hello,

my requirement is to auto confirm users without sending them any emails (no temporary password,no verification code) but they should have facility to reset password, please let me know if  this is possible  with cognito.

Thanks

**Comment by gitjeff05** [comment]
According to the docs, [you can use a PreSignUp AWS Lambda function to automatically confirm your users](http://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-javascript.html#tutorial-integrating-user-pools-confirm-users-javascript). However, I think you'll eventually have to verify an email/phone if you want them to be able to reset their password. For more information, read [Confirming User Accounts Without Verifying Email or Phone Number](http://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html) and note the caveat:

> While this approach is convenient for users when they're getting started, we recommend auto-verifying at least one of email or phone number. Otherwise the user can be left unable to recover if they forget their password.

**Comment by abhishekpalavancha** [comment]
Thanks for response , So if i verify the user while resetting password do they get verification code twice one for verifying the email and other for resetting password or only with one verification code can be used to do both verifying email and resetting password.

**Comment by chetanme** [comment]
A user cannot use forgot/reset password flow both email and phone number are unverified. 

Our documentation is little behind on this, but we have added the functionality in the PreSignUp trigger so that you can use autoVerifyEmail or autoVerifyPhone flags in lambda trigger response to verify email and/or phone numbers. You can see these flags today if you print the event source in your PreSignUp trigger source. We are in process of updating our docs.

This will allow you to auto confirm your users and auto verify a delivery mechanism for them. A user will be able to use Forgot password flow immediately after SignUp if you do this.

**Comment by ghost** [comment]
Even thouth I'm using a pre-signing lambda function to auto-confirm my user accout I have an error message when I try to reset the password.

I have this error message :

>  InvalidParameterException: Cannot reset password for the user as there is no registered/verified email or phone_number

How could I fixe it @chetanme ?
