### ISSUE TITLE
What is the purpose of AuthenticationDetails?

### ISSUE THREAD

**Issue by SteveALee** [aws/amazon-cognito-identity-js#36]
As far as I can see only the `user` and `password` props of [AuthenticationDetails](https://github.com/aws/amazon-cognito-identity-js/blob/master/src/AuthenticationDetails.js) are [used](authenticateUser) so why not just use the plain JS object used to construct AuthenticationDetails?

**Comment by SteveALee** [comment]
Probably better to say the `ValidationData` never seems to be  set

**Comment by chetanme** [comment]
Setting the ValidationData is a developers choice if they need to pass this map to their PreAuthentication lambda trigger. If they do not set this we assume it is null and we do not pass anything to the lambda trigger and if it exists SDK passes that to the service and service passes that on to developers Lambda function.

The idea of having a AuthenticationDetails object is to keep the Cognito client SDK consistent across platforms like Android and iOS. We understand this add some additional code in developers app to create this object instead of a simple JS object but this makes it easier for developers to understand Cognito usage across platforms and helps us maintain these SDKs easily. Hope this

**Comment by SteveALee** [comment]
Thanks!

>  if it exists SDK passes that to the service and service passes that on to developers Lambda function. 

I didn't spot it being used at all in the code here, let a alone pass it on. I probably just missed it

> the Cognito client SDK consistent across platforms like Android and iOS

+1. Though when trying to understand the sync options I saw android has a wait for connection api and others don't

So this brings me on to another more general confusion I have. How exactly does the SDK in this repo fit in with the other javascript SDKs? As someone who this is the contact with AWS i'm trying to learn all AWS concepts from the code and example here as well as the many iOS and Android only docs I find. I did find some pages with examples for 4 platforms but now cant find them. Ithink that was cognito but may have been Dynamo.

More specifically,  my next step is to use Cognito Sync, then S3 for images and I need to figure how the cognitoID (or other tokens) I get here is used with those APIs. Perhaps another simple example in the read me would sort that out? Plus pointers to the right JS docs for otehr APIS while the JS API is getting more fully integrated into the docs.

Is the the full Cognito JS API or just UserPools, which is what I understood. Does it replace parts of other APIS.

Also I read for other platform APIs the auth token needs to be refreshed, but there is no mention of that in the README and not much in the code.

Sorry that's a lot of Qs in one issue.
thanks

**Comment by chetanme** [comment]
It is only UserPools part of Cognito and because the feature is in beta, it is not very tightly coupled with the AWS JS SDK. As we go GA, the relation between Cognito user pools and other AWS services will be more simpler and clear.

To use other AWS services you need to integrate Cognito user pools with Cognito federated identity for temporary AWS credentials and then use those credentials to contact any other AWS service. These instructions are in our [developer guide](http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html) already. 

The process of refreshing the tokens is also part of our [developer guide for Using tokens](http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html).

**Comment by SteveALee** [comment]
@chetanme Great. I realise I'm trying it early and as a AWS noob :) I hope my input is useful.

> To use other AWS services you need to integrate Cognito user pools with Cognito federated identity for temporary AWS credentials and then use those credentials to contact any other AWS service. These instructions are in our developer guide already. 

Aha! I missed that one example. I thought I had read all the docs. The `Logins:` key was want I could not find. I was mainly going by the examples in the UserPools API readme - perhaps copy that there too? Thanks!

> The process of refreshing the tokens is also part of our developer guide for Using tokens.

OK. For some reason I seemed to have the experience that `session.isValid` returned true after a day. However It is possible I some how re-logged in. I'll explore more once I get access to other services, not just login / out working

Thanks again for your patience.

One thought: in the main documentation I wonder if making a distinction between mobile and javascript APIs is useful? Like many I'm working on mobile web apps so all the requirements of iOS and Android apply (eg broken connectivity). As long as the Javascritp API addresses those and is not desktop centric I'm happy. Currently though I can easily find links to Mobile API in the main docs but not Javascript - perhaps they could be merged?

**Comment by chetanme** [comment]
Glad I could help and yes, I agree our developer guide is missing the link to crucial JavaScript documentation and we are working on improving those on a daily basis. Thanks for pointing this out.

**Comment by borosio** [comment]
Hi, @chetanme .  Do you know what happen if my user is registered in my userpool (with pre-signup trigger he was confirmed), but my user did not confirm the email (email_verified is false) and he does not remember his password? Is it possible delete the user from my userpool without authentication process? 
Or is it possible change email_verified to true without send email with a pre-signup trigger, like the event.response.autoConfirmUser = true?

**Comment by chetanme** [comment]
Users without authentication can only be deleted through our admin API, [AdminDeleteUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminDeleteUser.html), which should be called from your back end or from the AWS Management Console.

**Comment by borosio** [comment]
Hi, @chetanme. How can I change email verified = true after an user is confirmed through pre-signup trigger? We need that ours users can be authenticated almost with username. My userpool is configured with email required. If use resendConfirmCode  to send email with resendcodeconfirmation, I get message User have been confirmed.
