### ISSUE TITLE
error cannot find name 'Buffer 

### ISSUE THREAD

**Issue by RashmiPandey** [aws/amazon-cognito-identity-js#460]
I am developing a Nodejs mobile app using Ionic, Angular 2 and Aws Cognito. After  integrating  amazon-cognito-identity-js, it shows error cannot find name 'Buffer'

AWS Cognito installed using the command: npm  install --save amazon-cognito-identity-js

 After adding following statement:
 import { CognitoUserPool, CognitoUserAttribute, CognitoUser, AuthenticationDetails } from 'amazon-cognito-identity-js'

getting the following error: 
 Cannot find name 'Buffer'.
 L1031:  export type _Blob = Buffer|Uint8Array|Blob|string;
 L1032:  export type Boolean = boolean;

**Comment by itrestian** [comment]
How are you getting the main aws sdk and what version are you getting?

**Comment by nwayve** [comment]
@RashmiPandey Double check your tsconfig.json file's typeRoots and types.  If typeRoots is declared, it needs to have "node_modules/@types" included.  If types is defined it needs to have "node" included.  More in-depth explanation [here](https://stackoverflow.com/a/45089715/354317) with reference to tsconfig documentation.  You'll also want to make sure you've installed the Node Typescript definitions module: `npm install --save-dev @types/node`
```json
{
    "compilerOptions": {
        "typeRoots": [ "node_modules/@types" ],
        "types": [ "node" ]
    }
}
```
amazon-cognito-identity-js brings in aws-sdk as a dependency but the issue is `Buffer` and other Node specific types that amazon-cognito-identity-js references aren't being found.

**Comment by mkamrani** [comment]
@nwayve Had the same issue, your solution was the only one worked for me.

**Comment by prasanna-arokee** [comment]
Hi guys! I am facing the same issue. Please help me fix this issue:

 Typescript Error
Cannot find name 'Buffer'.

  | export type CertificateBody = string;
  | export type CertificateBodyBlob = Buffer\|Uint8Array\|Blob\|string;
  | export type CertificateChain = string;
