### ISSUE TITLE
Check unique Email

### ISSUE THREAD

**Issue by jnnck** [aws/amazon-cognito-identity-js#511]
Hi,

Is there a way to check if an email is already in use? 

Use case: i want to check unique email on signup with ajax.

Kr,
Jannick

**Comment by prem911** [comment]
You may use adminGetUser api

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminGetUser-property

This takes the username as param.
Are you using email as alias or username?

**Comment by ankitnaugariya** [comment]
Yes. As @prem911 has pointed, you can use email as alias. This would ensure that emails are unique in the userpool.

**Comment by MatteCarra** [comment]
I've a userpool with email set as an alias, but I have three users with the same email.
Only the last user that signed up with the same email can login with his email and password.

**Comment by Balta-zar** [comment]
I have same problem as @MatteCarra and also I found some strange behavior. If verification type is link (selected in message customizations) than there is an error and user is not able to validate email if user with same email exists. On the other hand, if verification type is code user is able to validate email (confirm registration with use case 2 from documentation for  Amazon Cognito Identity SDK for JavaScript) regardless of old user with same email address. Also, when user validates email with new username then all other users with same email will have field email_verified set to false. Is this an expected behavior, or I'm doing something wrong?
**Edit**: I'm sorry. After few days of unsuccessful attempts I finally found solution and the solution is extremely easy. Second parameter in confirmRegistration method needs to be false.

**Comment by clintfoster** [comment]
This issue has come up many times (for good reason since Cognito has never addressed it in a reasonable way). It seems clear that the great majority of the time if someone tries to sign up again with the same email alias, it is either because they forgot they already have an account, or they forgot their password and they're trying to create another account with the same email address (usually not what's wanted since application data associated with the original account would be lost). It seems clear there should be a configuration option on the User Pool to return an error rather than silently creating another user (enabled by default for new user pools). The application could then warn the user if an account already exists for the email alias, and offer to reset the password. This is surely what is wanted nearly all of the time.

Related discussion:

- [Force signUp() to fail if user already exists with same email alias](https://forums.aws.amazon.com/message.jspa?messageID=740154#740154)
- [Implement pre-signup trigger in Java](https://forums.aws.amazon.com/thread.jspa?messageID=778388)
