### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by southpolesteve** [aws/amazon-cognito-identity-js#6]
Are there plans to publish this module to npm? We are trying to integrate this into a build process and having it on npm would be ideal

**Comment by itrestian** [comment]
Hi Steve,

As a general rule, we don't comment on the future direction of products and features, but I will definitely mention this within the team as we are always interested in hearing details about different use cases our users target.

Ionut.

**Comment by AlexMcConnell** [comment]
Are there use cases where it wouldn't be better to have it available via npm?

**Comment by sarah-pixvana** [comment]
Some feedback for the future production:

Agreed that it would be awesome to have this on npm as a completed package. Right now I am doing a lot of hacks to get the sdk + all required libraries working with our build. Is there any reason that all the libraries it is dependent on aren't already included in the package (jsbn,moment, etc?). The current workflow to just get started is very messy.

**Comment by behrooziAWS** [comment]
Thanks for the feedback Sarah, the way it is packaged today was the quickest way to work through licensing.  We will add a feature request to streamline the packaging to make it more turn-key.

**Comment by luckybroman5** [comment]
For a node Env Setup, pease see my fork: https://github.com/luckybroman5/amazon-cognito-identity-js/tree/node

**Comment by AlexMcConnell** [comment]
Your node Env Setup is freezing for me on cognitoUser.authenticateUser() (It appears to be something inside this.calculateA(this.smallAValue); )

Also, there are a couple of typos right at the beginning of the node setup section of the readme.

**Comment by luckybroman5** [comment]
Hi @AlexMcConnell,

I have ran into that issue as well. It is a problem with the big integer library. Specifically the `modPow()` function. If you look it is doing a calculation on a massive number. I'm using this for a proof of concept at work, not for production. I'd imagine whatever Amazon comes out with for node support will be better than what I do.

If you wait long enough (About 11 seconds) It will process. One way I have found to get around this issue is to initialize the `new AWSCognito.CognitoIdentityServiceProvider.AuthenticationHelper(this.pool.getUserPoolId().split('_')[1], this.pool.getParanoia());` function only once when the web server starts, then pass it in as a parameter upon the `cognitoUser.authenticateUser()` function call.

Another way I have been thinking about is to extract whatever the result is of the `modPow()` function and completely skip this step in the process.

Please take into account, that my fork is an open source contribution. If you see improvements, any PR's would be appreciated :)

**Comment by simonbuchan** [comment]
Can we get this up now that this is usable from bundlers? If only so install is `npm i -S aws-cognito-identity` not `npm i -S github:aws/amazon-cognito-identity-js` and the versioning benifits that gets.

**Comment by itrestian** [comment]
Just published the package to npm

https://www.npmjs.com/package/amazon-cognito-identity-js

**Comment by pvadam** [comment]
Fantastic, thanks!! But why does the minified version contains the `require` imports?

I'm bundling with webpack and then publishing in a web app. Since the file is minified, I wanted to add this library to the noParse list, but the docs on noParse says:

`The files are expected to have no call to require, define or similar. They are allowed to use exports and module.exports.` [see it here](https://webpack.github.io/docs/configuration.html#module-noparse)

Are there any plan to remove the the requires? They were not yet there a couple of months ago..

I meant the `dist/amazon-cognito-identity.min.js` file.

**Comment by simonbuchan** [comment]
@itrestian the `-js` is a little redundant :)

@pvadam Sorry, this all moved faster than I expected! The dist bundle is now a webpack UMD: #108, so it can be used either in `<script>` with the old behavior or in bundlers to behave as a module, though I broke the loose `jsbn` usage, fix in #112 (sorry!) - you could try using the npm `jsbn` as a script instead?

I'll get a PR up adding webpack usage to the readme later today, but the PR description has a working webpack config.

`noParse` should still work in theory, despite the message, since the `require()` calls are in the non-module (`<script>`) handling of UMD, but I haven't tried it.

To keep the current behavior of `noParse`, you could instead try:
- `'script!amazon-cognito-identity-js'`, behaves similarly to `noParse` it seems
- `'imports?require=>false!amazon-cognito-identity-js'` which should disable the UMD treating it as a module

I suggest importing it as a module instead:

```
import { CognitoUserPool } from 'amazon-cognito-identity-js`;
```

Though for now it expects `aws-sdk` to export `AWS`, which it doesn't by default - see the PR description.

**Comment by pvadam** [comment]
@simonbuchan Should the import of the npm module work with typescript out of the box or is there anything else I have to set?

After installing it with npm and compiling my code, `awesome-typescript-loader` gives the error:

`Cannot find module 'amazon-cognito-identity-js'.`

even though importing e.g. `aws-sdk` is perfect. I have tried to import it as you have suggested:

`import { CognitoUserPool } from 'amazon-cognito-identity-js';`

**Comment by simonbuchan** [comment]
@pvadam that looks like the typescript can't find typings error, webpack not finding the module looks quite different.

Did you install the typings for `aws-sdk`?

**Comment by pvadam** [comment]
@simonbuchan yes, my bad, sorry!

What helped me in solving the issue (beside the missing typings) was your comment about the proper setup: https://github.com/aws/amazon-cognito-identity-js/issues/48#issuecomment-235423796

If someone would be interested, here is a very simple typings declaration I have created:

```
declare module "amazon-cognito-identity-js" {

  import { ClientConfig } from "aws-sdk";

  export class CognitoUser {
    /**
     * Returns the current session details.
     */
    public getSession(callback: Function): void;

    /**
     * Authenticates the user.
     */
    public authenticateUser(params: any, callbacks: any): void;

    /**
     * Confirms the user after sign up
     * with the confirmation code received
     * by email or phone.
     */
    public confirmRegistration(code: string, somethingWhichIsTrue: boolean, callback: Function): void;

    /**
     * Confirms the user after sign up
     * with the confirmation code received
     * by email or phone.
     */
    public resendConfirmationCode(callback: Function): void;
  }

  export class CognitoUserPool {

    /**
     * Cognito user pool id.
     */
    public userPoolId: string;


    client: CognitoIdentityServiceProvider;

    /**
     * Constructs a new CognitoUserPool object
     * @param {object} data Creation options.
     * @param {string} data.UserPoolId Cognito user pool id.
     * @param {string} data.ClientId User pool application client id.
     * @param {int=} data.Paranoia Random number generation paranoia level.
     */
    constructor(data: any);

    public getCurrentUser(): CognitoUser;

    /**
     * @returns {string} the user pool id
     */
    getUserPoolId(): string;

    /**
     * @returns {string} the client id
     */
    getClientId(): string;

    /**
     * @returns {int} the paranoia level
     */
    getParanoia(): number;

    /**
     * sets paranoia level
     * @param {int} paranoia The new paranoia level.
     * @returns {void}
     */
    setParanoia(paranoia: number): void;

    /**
     * @typedef {object} SignUpResult
     * @property {CognitoUser} user New user.
     * @property {bool} userConfirmed If the user is already confirmed.
     */
    /**
     * method for signing up a user
     * @param {string} username User's username.
     * @param {string} password Plain-text initial password entered by user.
     * @param {(AttributeArg[])=} userAttributes New user attributes.
     * @param {(AttributeArg[])=} validationData Application metadata.
     * @param {nodeCallback<SignUpResult>} callback Called on error or with the new user.
     * @returns {void}
     */
    signUp(username: string, password: string, userAttributes: Array<any>, validationData: Array<any>, callback: Function): void;

    /**
     * method for getting the current user of the application from the local storage
     *
     * @returns {CognitoUser} the user retrieved from storage
     */
    getCurrentUser(): CognitoUser;
  }

  export class CognitoIdentityServiceProvider {

    public config: ClientConfig;
  }
}
```

**Comment by paulsson** [comment]
@pvadam I am interested in getting TypeScript typings for this.  Have you done much more to define complete typings?  It looks like the typings you provided above are very limited.

I'm getting the aws-sdk-js typings from:
https://github.com/ingenieux/aws-sdk-typescript
since neither AWS nor DefinitelyTyped are providing them.

I'm trying to strike up this conversation in the 2 repositories:
https://github.com/aws/amazon-cognito-identity-js/issues/115
and
https://github.com/ingenieux/aws-sdk-typescript/issues/20

@simonbuchan how can we do a TypeScript import as you suggested when no typings exist for amazon-cognito-identity-js?
`import { CognitoUserPool } from "amazon-cognito-identity-js";`

**Comment by simonbuchan** [comment]
@paulsson Do them yourself? At minimum:

```
declare module "amazon-cognito-identity-js" {
  var value: any;
  export = value;
}
```

Or in Typescript 2.0, just `declare module "amazon-cognito-identity-js";`

I'm all for Typescript, but manually written types are an extra maintainance burden and are just as likely to get out of date, so unless Amazon or sormeone else are willing to step up....

Or of course, the repo is converted to Typescript, then all the problems go away :)

**Comment by pvadam** [comment]
@paulsson Yes, I have only included the properties and methods I have used, so that's all I have.

BTW as far as I remember, you do not need `aws-sdk-typescript`, because the following works properly for `aws-sdk`:

```
typings install dt~aws-sdk --global --save
```

or if you are already using @types references

```
npm install @types/aws-sdk --save-dev
```

For `amazon-cognito-identity-js`, you have do some manual work.

**Comment by itrestian** [comment]
Updated the latest version on npm. Closing.
