### ISSUE TITLE
Cognito Confusion

### ISSUE THREAD

**Issue by singledigit** [aws/amazon-cognito-identity-js#60]
Hey Guys, first of all this is great. Really cool stuff and excited to be using it!!

Here is my issue/comment/concern. The examples shown here all include setting the Cognito Identity pool. I understand this will be used if I want federated access to the rest of AWS services. However, if I am understanding this correctly, I do not need a Cognito Identity Pool to simply authenticate my application.

Is this correct?

I bring up this question because I have gotten the authentication working beautifully, however, when I make a secondary call to get user attributes, I am getting `Error: User is not authenticated`.

I want to make sure I am understanding that to simply authenticate against the User Pool and access user attributes, I do NOT need to be federated against a Cognito Identity Pool.

Either way, it would be great if this were clearer. It seems to me there is an overall confusion of User Pools verses Identity Pools.

Thanks again for the great work here!!

**Comment by MarkMercAWS** [comment]
Hello,

You are correct. a User does **not** need to get AWS credentials to access their own attributes within Cognito User Pools.

You successfully registered the user, and confirmed the user's email/phone number, then signed-in the user?

-Mark

**Comment by dksheffield** [comment]
I'm kind of in the same boat but my use case is different. Once I authenticate a user I can do all of the authenticated examples that you have posted. If I refresh the web page > I can use cognitoUser.getSession() and I can get the session and see that the session is valid, but I'm not able to make authenticated calls again unless I re-authenticate with a username and password.

Is this the expected behavior?

My use case is that when users request a page - i check some user attributes in the user pool and determine if they have access on the front end to view the page. So my problem is after I authenticate then refresh the page for whatever reason i'm not able to check the attributes without the user re-authenticating even though I have a valid session and valid tokens. 

Thanks

**Comment by chetanme** [comment]
@dksheffield Your use case should be supported. Are you calling [clearCachedTokens](https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js#L483) somewhere in your app? The only reason your user would need to re-authenticate is if the cached credentials have been removed from local storage.

@singledigit I would ask the same question to you too. Is there a call to [clearCachedTokens](https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js#L483) somewhere?

**Comment by dksheffield** [comment]
I did figure out my problem, I was calling get user and then trying to get attributes. I changed it to get user then get session then get attributes. Once I added the get session then I was good to go. Thanks!

**Comment by chetanme** [comment]
@dksheffield Glad you worked it out.

@singledigit Let us know if you are still running into problems.

**Comment by kelvanince1** [comment]
@dksheffield 
I have the exact same problem as you had. Do you mind sending a code snippet of the get session solution you mentioned? 
You might just save me about fifteen hours work. 
Thanks.

**Comment by dksheffield** [comment]
I think this is it, I had to get the user, then get the session, then I was able to move forward. Maybe this will help...

https://gist.github.com/dksheffield/8ead7efa7cc63059a702214bf0975298
