### ISSUE TITLE
Custom Messaging seem not working

### ISSUE THREAD

**Issue by ryutamaki** [aws/amazon-cognito-identity-js#99]
I have tested user pool custom messaging functionality and seems not working now.
I did test static messaging and custom messaging using lambda function but it don't send me email.
Could you please take a look this??

I'm pressure to give you more information, please tell me what you wanna know.

**Comment by chetanme** [comment]
Just enabling Custom Message trigger will not send an email on user actions. Custom message trigger is meant to customize the message which is already going out in email or SMS.

To send out emails, you need to turn on **Auto Verification** by email and/or phone number on your user pool and supply and email for a user during SignUp or UpdateUserAttributes. If this preconditions are met, the service automatically sends and email, otherwise stays silent and just performs the operation which was called.

**Comment by ryutamaki** [comment]
Where can I turn on Auto Verification??

**Comment by itrestian** [comment]
Basically in the user pool creation section, you can select either email or phone number or both for which we send verification codes that can be used to verify the attribute.

![auto verif](https://cloud.githubusercontent.com/assets/18453633/17498688/bb27bbda-5d7d-11e6-9f98-73ed56820149.png)

**Comment by ryutamaki** [comment]
I found the reason why email is not sent.
I am using auto-confirm-user using lambda trigger and if user was confirmed, the email is not sent from user pool

And there is another issue.
I try to send email and I got an error below.

```
at 'emailBody' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*\{####\}[\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*
```

We are using Japanese in emailBody and Japanese is not supported.

**Comment by itrestian** [comment]
Unicode should be supported so that should include Japanese characters. 

Are you sure you are including {####} in your email body? That is used to specify to our system where the verification code should be inserted.

**Comment by ryutamaki** [comment]
I'm really appreciate for supporting unicode.

I'm using `event.request.codeParameter` for inserting confirmation code in an email we wanna send.
I create lambda trigger by referring to this article http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#aws-lambda-triggers-custom-message-example

**Comment by chetanme** [comment]
What call did you see this error from? Can you give us some sample request ids with time stamp for this?

If you can give us the sample text of what you are trying to send in the email, that will also help us debug this further.

**Comment by ryutamaki** [comment]
I'm really sorry for late replying.

Here is error messages I got.
And, I can send normal Japanese message. Maybe, there are some of special characters which can not be sent.

```
failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}\\s*]*\\{####\\}[\\p{L}\\p{M}\\p{S}\\p{
N}\\p{P}\\s*]*'
```

**Comment by ryutamaki** [comment]
I found the reason. If my email message has `Double-byte space` , the above error occurs.

**Comment by itrestian** [comment]
So is this still an issue? It seems you figured out how to get it working.

**Comment by ryutamaki** [comment]
It would be better if you fixed this problem. However this is not so big problem for me.

**Comment by ryutamaki** [comment]
@itrestian 
I found this issue become a big problem if I change custom message on GUI in cognito user pool console.

Here are screen shots for it.
If I use Japanese character, this regex prevent me to save message.
I found forum post about this and that might not be proceeded to.
https://forums.aws.amazon.com/thread.jspa?messageID=739305&#739305

Could you bring up this problem again and take some time to fix this?

- input: ![image](https://cloud.githubusercontent.com/assets/762414/24191730/f5a8e162-0f2f-11e7-806d-74de7cc979bb.png)
- error: ![image](https://cloud.githubusercontent.com/assets/762414/24191646/c14425e4-0f2f-11e7-9ec7-584755493df5.png)

Thanks

**Comment by takaoh717** [comment]
If you have not yet resolved, You can use Japanese character by AWS CLI.

For example
`$ aws cognito-idp update-user-pool --user-pool-id {your pool-id} --email-verification-subject '{subject}' --email-verification-message "{message}"`

**Comment by ryutamaki** [comment]
I can see the update for Japanese!
So much thank to you all!

**Comment by ryutamaki** [comment]
just FYI, I was using this script to update cognito user pool custom massage
`aws cognito-idp update-user-pool` updates ALL of the configurations for your user pool so that you must set your configuration which is not same as default value.

```
aws cognito-idp update-user-pool --user-pool-id {{your user pool id}}\
    --policies \
    '{ 
        "PasswordPolicy": {
            "MinimumLength": 8,
            "RequireUppercase": true,
            "RequireLowercase": true,
            "RequireNumbers": true,
            "RequireSymbols": false
        }
    }' \
    --auto-verified-attributes 'email' \
    --email-verification-subject 'タイトル' \
    --email-verification-message 'メッセージ' \
    --admin-create-user-config \
    '{
        "AllowAdminCreateUserOnly": true,
        "UnusedAccountValidityDays": 30,
        "InviteMessageTemplate": {
            "SMSMessage": "Your username is {username} and temporary password is {####}.",
            "EmailSubject": "タイトル",
            "EmailMessage": "メッセージ"
        }
    }'
```

**Comment by RameshRM** [comment]
Hi, 

`CustomMessage` from the `lambda` doesnt seem to work reliably , i do see the custom messages work some times but not always.

All i have in my lambda is a simplest `foo`

```
    event.response.emailMessage = 'Foo';
    context.succeed(event);    
```

Any pointers will help 

Thx

**Comment by mattcoll** [comment]
@itrestian @chetanme Just wondering if anyone can shed some light on this topic.
I am having a similar issue (same error) - 
`InvalidParameterException: 1 validation error detected: Value`
`at 'emailBody' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*\{####\}[\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*`

![screenshot](https://user-images.githubusercontent.com/19816080/34618397-904295e6-f28e-11e7-9cb4-b96194e794e4.jpg)

I have attached the log from CloudWatch but due to privacy blank most of it out. But you can see that the codeParameter and userName are being inserted correctly.

I am creating a custom message using cognito trigger to execute my lambda. Im 99% sure I have covered all polices around this. This is my lambda which calls a function that returns a string - normal string for basic message and string with html elements for html message.
```
if(event.triggerSource === "CustomMessage_AdminCreateUser") {
            event.response.emailSubject = 'Title - Admin';
            if (event.request.userAttributes['custom:basicMail'] === "true") {
                event.response.emailMessage = adminBasicMailMessage( event.request.usernameParameter,
                         event.request.codeParameter);
            } else {
                event.response.emailMessage = adminHtmlMailMessage(event.request.usernameParameter,
                    event.request.codeParameter);
            }
        }
        else if(event.triggerSource === "CustomMessage_SignUp") {
            event.response.emailSubject = 'Title - Sign_Up';
            if (event.request.userAttributes['custom:basicMail'] === "true") {
                event.response.emailMessage = userBasicMailMessage(event.request.usernameParameter,
                    event.request.codeParameter);
            } else {
                event.response.emailMessage = userHtmlMailMessage(event.userName,
                    event.request.codeParameter);
            }
        }
```
I have exactly the same strings for both Admin and Sign_up.
The weird thing is if I create user through Admin it generates html email fine. Which confuses me cause surely if there was something wrong with the emailBody it would throw the error in Admin too.

I know this probably isn't the spot for this comment, but I am stuck.
Any help would be much appreciated!
Thanks
